### PR TITLE
Add namespace-scoped RBAC support

### LINKED ISSUE #5: Default right now is only ClusterRole
We should provide the ability to install ClusterRole or Role methods, allowing the operator to manage either all namespaces or just the one it's installed into, and ensure that those options are exposed however the custom catalog source exposes them.

### PR DESCRIPTION
**Pull request by andykrohg**
Fixes #5

### CODE REVIEW

**Comment by andykrohg** [comment]
I have the namespaced RBAC working locally, but I still need to instrument the operator config to offer both cluster-wide and namespaced installations. Oh, and something's up with the build - I'll look into that too.

**Comment by jharmison-redhat** [comment]
@andykrohg Once this passes, if the molecule test changes make sense to you, we can merge and I'll rebase and resolve conflicts with the other PR then add specific tests to validate namespace scope enforcement.

I believe it to be functional right now, but I'd like to be sure.

**Comment by jharmison-redhat** [comment]
It creates two separate clusters, serially, tearing down all resources in between.

**Comment by andykrohg** [comment]
Alrighty - may want to circle back on this once we build out the molecule tests a bit more. For now, lgtm

**Pull request merged**
